FROM renskiy/cron

RUN  apt-get update \
  && apt-get install -y wget curl \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.03.1-ce.tgz && \
tar --strip-components=1 -xvzf docker-17.03.1-ce.tgz -C /usr/local/bin